### ISSUE TITLE
Support `'method'` args to `rankdata` and `nanrankdata`

### ISSUE THREAD

**Issue by ssanderson** [kwgoodman/bottleneck#103]
[`scipy.stats.rankdata`](http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.stats.rankdata.html) supports multiple methods of resolving ties.  It'd be awesome if bottleneck emulated these options (I'm specifically interested in the `'ordinal'` option, but once you have two it's probably better to just have full compat).

I'd be willing to take a stab at this if there's interest in supporting it.

**Comment by kwgoodman** [comment]
I guess it would depend on how much, if any, it slows down calculations with the default tie-braking behavior and how much code complexity it adds.

It would not add much code complexity to add if...elif statements to the main ``for`` loop. But I don't know how much time it adds to have an extra if statement for each element of the array.

For something like this, your best bet is to hack something together and report the results. Then we can decide if it is worth adding.

**Comment by jennolsen84** [comment]
Putting an if in the middle of a loop can be tricky.  If the branch predictor mispredicts (this will be CPU dependent), it can be bad... but only careful profiling will tell.

In C++, the better way to solve these types of issues is to use polymorphism and have two instances of the call/function and the right one gets called appropriately.  So, you pay a super tiny hit in the beginning, but have branchless code while looping

**Comment by kwgoodman** [comment]
I'm closing this one for now.
