### ISSUE TITLE
Why is bottleneck not merged into NumPy?

### ISSUE THREAD

**Issue by alexamici** [kwgoodman/bottleneck#109]
In the documentation and also searching the internet I didn't find any hint on why Bottleneck functions are so much faster than standard NumPy ones and if there is any plan to merge the more efficient versions into NumPy proper.

As a user I was quite surprised to learn that I needed a special package to have the efficient version of such basic operations. I guess there is a good reason and maybe a short paragraph in the README may be enough to clear the confusion.

**Comment by kwgoodman** [comment]
I'm not a numpy developer. But the smaller we make the auto-generated C code, the smaller we make the binary, and the more compatible we make the functions, the more likely numpy is to use some of this code at some distant time (if it is not already faster by then!).

Keep in mind that only some dtypes are accelerated, complex numbers have not been tested, and the function signatures are not the same as in numpy. Yeah, so bottleneck is special-use code.

**Comment by alexamici** [comment]
I can consider the issue resolved for me. I'd suggest to add a line to README to explain that bn is special-use code and for this reason we can expect it to be off numpy for the foreseeable future. Thanks!
