### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by Midnighter** [kwgoodman/bottleneck#112]
Since I'm working on this for my own project right now, are you interested in having `bottleneck` tested on Travis CI and AppVeyor? Since I recently had to return the laptop whereon I did the 32bit arch tests for you, those could be done as well. And while we're at it, those tests could be used to calculate coverage as well.

**Comment by kwgoodman** [comment]
Thank you for the offer.

I test bottleneck with tox. That has worked well for me. I think I'll stick with tox for now versus adding something new (Travis) to maintain.

**Comment by Midnighter** [comment]
That's fair although I use tox on Travis as well. It just means that you can test on Ubuntu and OS X on Travis, Python 2.x and 3.x, 64bit 32bit and the same on Windows with AppVeyor. Maybe that doesn't matter to you but it could improve reliability of bottleneck.

**Comment by shoyer** [comment]
I'm strongly in support of this. From the perspective of a potential contributor, having a continuous integration service hooked up makes me much more likely to write a patch. In my opinion, CI is on the basic list of software engineer best practices that every serious open source project should adopt.

**Comment by kwgoodman** [comment]
I don't have any experience with all this. When does it run? After every commit? On PRs? What about in branches that are not part of a PR?

You mentioned tox. Would it use the tox.ini file that already exists in bottleneck? Does tox run on windows?

What kind of things would trigger the need to change the init files (i.e. what's maintenance like)?

**Comment by Midnighter** [comment]
> I don't have any experience with all this. When does it run? After every commit? On PRs? What about in branches that are not part of a PR?

This is configurable. The default is to run the tests on every commit and PR to the master branch. You can adapt when the tests should be run and on which branches.

> You mentioned tox. Would it use the tox.ini file that already exists in bottleneck? Does tox run on windows?

Travis-CI (linux, OS X) and AppVeyor (Windows) can both be configured to run tox and thus make use of the `tox.ini`. However, the numpy package available is quite dated and installing it via `pip` takes a long time (it's also a PITA due to its dependencies). That is why I've set up a [test repository](https://github.com/Midnighter/compiled-extensions-ci) where I use miniconda instead. That's a minimal version of Anaconda and makes numpy quick and easy to install. Conda creates its own environments making tox superfluous. I looked at the `tox.ini` file and you don't do anything special in there, so it'd be easy to replace.

> What kind of things would trigger the need to change the init files (i.e. what's maintenance like)?

As long as testing continues to depend on `nose` and the `tools/test-installed-bottleneck.py` script you won't need to change anything. Of course, using conda, and hence dropping tox on the CI servers, means that the Travis and AppVeyor will need to be kept in sync. Since your `tox.ini` is so minimal I don't foresee a problem there, however.

**Comment by kwgoodman** [comment]
OK, let's give it a try. Perhaps we could start with Travis and see how that goes before adding AppVeyor.

**Comment by Midnighter** [comment]
> OK, let's give it a try. Perhaps we could start with Travis and see how that goes before adding AppVeyor.

Perfect. I'm still playing with AppVeyor and struggling with Travis 32bit at the moment. Expect a PR soon.

**Comment by Midnighter** [comment]
[Here's the documentation](https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches) on how Travis treats branches.

**Comment by Midnighter** [comment]
So, I was a little wrong. Any branch that contains a `.travis.yml` file in the root of the repository will be tested unless excluded as explained in the documentation.

You can see [on Travis-CI](https://travis-ci.org/Midnighter/bottleneck) that the tests now run in a little under 2 minutes and that there are 3 test failures. I'll open the pull request now.

**Comment by kwgoodman** [comment]
Travis seems to be running now. Thank you. Hopefully we can get 32 bit running at some point.

**Comment by Midnighter** [comment]
The docker containers run something like Ubuntu 12.04 I believe. So all that's needed is to activate multi-arch and install the necessary 32bit libraries. I've asked on SO, the conda list and gitter chat but no answers so far.

**Comment by kwgoodman** [comment]
Can we control which numpy version(s) to test against?

**Comment by Midnighter** [comment]
Yes, just put in `numpy==1.10` instead of `numpy` in the `.travis.yml` file.

**Comment by kwgoodman** [comment]
You were right about adding CI to bottleneck. It has been a big help.

You mentioned in #115:

> 
> For the separate pull request:
> 
> 1. I didn't find it earlier but pip has a --verbose option which gives you all the output that you wanted to see.
> 2. Running python setup.py sdist creates an archive like this: dist/Bottleneck-1.1.0.dev0.tar.gz which can then be installed with pip. I'd be happy to make a pull request that adapts those changes in the .travis.yml once you're satisfied with the state of the master branch.
> 
> Of course, that means you'd have to distribute the *.c source files. Otherwise you'd need to generate the source distribution using Cython, then uninstall Cython, and finally install the source distribution. Could be done with some fairly easy bash scripting.

I think both of these changes would be helpful. Note that `python setup.py sdist` now creates the C files automatically. Nice find on the verbose option. It will make build fails easier to diagnose.

I think we can drop python 3.4 testing and just do 2.7, 3.5.

I'm also interested in running a single flake8 test in a separate environment from the unit tests (say py2.7). That way I'll know a PR is flake8 clean.

**Comment by kwgoodman** [comment]
Travis is running nicely. I'll close this issue. If we want to work on more CI stuff, like AppVeyor, we can open a new issue.
