### ISSUE TITLE
running bottleneck with multiple threads

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#118]
This is a continuation of the discussion that started towards the end of issue #111.

**Comment by jennolsen84** [comment]
(continuing from other thread).  OpenMP is good choice, I haven't worked with it personally so I can't comment.

**Comment by Midnighter** [comment]
I never worked out for myself what `numexpr` does but it might be worth exploring further.

**Comment by jennolsen84** [comment]
unfortunately, `numexpr` is hard to grok, and the maintainers are really busy... they have some sort of VM, and do a some useful work to avoid temporaries.  I think the approach used in https://github.com/shoyer/numbagg project has some good potential to take advantage of parallelization and removing temporaries at the same time.  They recently made available guvectorize's target=parallel in the free version of numba :). Perhaps @shoyer can comment.
