### ISSUE TITLE
Proposal for new design of bottleneck internals

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#123]
In the current design we do this to add the function bn.nanmean to bottleneck (I'll only show the float version, you'd also need to add the integer version):
```

@cython.cdivision(True)
cdef object nanmean_all_DTYPE0(np.flatiter ita, Py_ssize_t stride,
                               Py_ssize_t length, int int_input):
    # bn.dtypes = [['float64'], ['float32']]
    cdef Py_ssize_t i, count = 0
    cdef DTYPE0_t asum = 0, ai
    with nogil:
        while PyArray_ITER_NOTDONE(ita):
            for i in range(length):
                ai = (<DTYPE0_t*>((<char*>pid(ita)) + i * stride))[0]
                if ai == ai:
                    asum += ai
                    count += 1
            PyArray_ITER_NEXT(ita)
    if count > 0:
        return asum / count
    else:
        return NAN

@cython.cdivision(True)
cdef ndarray nanmean_one_DTYPE0(np.flatiter ita,
                                Py_ssize_t stride, Py_ssize_t length,
                                int a_ndim, np.npy_intp* y_dims,
                                int int_input):
    # bn.dtypes = [['float64'], ['float32']]
    cdef Py_ssize_t i, count
    cdef DTYPE0_t asum = 0, ai
    cdef ndarray y = PyArray_EMPTY(a_ndim - 1, y_dims, NPY_DTYPE0, 0)
    cdef np.flatiter ity = PyArray_IterNew(y)
    with nogil:
        if length == 0:
            while PyArray_ITER_NOTDONE(ity):
                (<DTYPE0_t*>((<char*>pid(ity))))[0] = NAN
                PyArray_ITER_NEXT(ity)
        else:
            while PyArray_ITER_NOTDONE(ita):
                asum = 0
                count = 0
                for i in range(length):
                    ai = (<DTYPE0_t*>((<char*>pid(ita)) + i*stride))[0]
                    if ai == ai:
                        asum += ai
                        count += 1
                if count > 0:
                    asum = asum / count
                else:
                    asum = NAN
                (<DTYPE0_t*>((<char*>pid(ity))))[0] = asum
                PyArray_ITER_NEXT(ita)
                PyArray_ITER_NEXT(ity)
    return y
```

Under the new proposal here's the code you'd write instead:
```
@cython.cdivision(True)
cdef inline DTYPE0_t nanmean_DTYPE0(char *p,
                                    Py_ssize_t stride,
                                    Py_ssize_t length,
                                    int int_input) nogil:
    # bn.dtypes = [['float64'], ['float32']]
    cdef Py_ssize_t i, count = 0
    cdef DTYPE0_t ai, asum = 0
    for i in range(length):
        ai = (<DTYPE0_t*>(p + i * stride))[0]
        if ai == ai:
            asum += ai
            count += 1
    if count > 0:
        return asum / count
    else:
        return NAN
```

The code is in the `minty_fresh` branch. I only ported nansum and nanmean (called nansum2 and nanmean2 in the branch).

When the length of each dimension of the array is large, performance is the same as before:
```
In [1]: a=np.random.rand(1000, 10000)
In [2]: timeit bn.nanmean(a)
100 loops, best of 3: 7.89 ms per loop
In [3]: timeit bn.nanmean2(a)
100 loops, best of 3: 7.86 ms per loop
```

For 1d arrays the overhead has been reduced:
```
In [4]: a=np.random.rand(10)
In [5]: timeit bn.nanmean(a)
1000000 loops, best of 3: 226 ns per loop
In [6]: timeit bn.nanmean2(a)
10000000 loops, best of 3: 184 ns per loop
```

For reduction of 2d (or higher) arrays with `axis=None`, overhead has increased because the rewrite uses PyArray_Ravel:
```
In [7]: a=np.random.rand(10,10)
In [8]: timeit bn.nanmean(a)
1000000 loops, best of 3: 325 ns per loop
In [9]: timeit bn.nanmean2(a)
1000000 loops, best of 3: 382 ns per loop
```

For repeated calls to the new inline function where each call does hardly any work, performance has decreased (not sure why; I don't even know if the inlining is taking place):
```
In [10]: a=np.random.rand(1000000,2)
In [11]: timeit bn.nanmean(a, 1)
100 loops, best of 3: 5.28 ms per loop
In [12]: timeit bn.nanmean2(a, 1)
100 loops, best of 3: 5.96 ms per loop
```

Adding a new reduction function to bottleneck is rare. So I'd only want to use the new design if we can improve the performance of the last two cases. On the other hand maybe the new design would make it easier to do things like optimize for reduction along a non-fast axis.

**Comment by kwgoodman** [comment]
I've asked the compiler to inline a function that is impossible to inline. At compile time the function I want to inline into doesn't know what the function to inline is until runtime (it is passed in as a function pointer).

To fix that I could have the bottleneck templating system insert the code and automate the process of wrapping the inline functions with all the `while PyArray_ITER_NOTDONE(ita)` stuff.

The function that needs the code inserted into it is `one_DTYPE0`. We'd need a unique version of that function for every function (nansum, nanmean, etc) crossed with every dtype (int32, int64, float32, float64). It would bloat the binary size of this proposal to be the same as current master is my guess.

I guess the proposal just got a bit more complicated but would automate the boilerplate code. Not sure it is worth it.

**Comment by jennolsen84** [comment]
Regarding function pointers and inlining, I remember Bjarne Stroustrup saying that C++'s sort() was faster than qsort because it didn't use function pointers.  Someone did a benchmark here:

```
http://www.martin-ueding.de/en/programming/qsort/index.html
```

**Comment by kwgoodman** [comment]
I think I'll abandon this proposal for now.

It did occur to me, however, that it could be adapted to allow user defined functions with something like this:
```
@bottleneck.reduce(dtypes = [['float64'], ['float32']])
cdef DTYPE0_t nanmean_DTYPE0(char *p,
                             Py_ssize_t stride,
                             Py_ssize_t length,
                             int int_input) nogil:
    cdef Py_ssize_t i, count = 0
    cdef DTYPE0_t ai, asum = 0
    for i in range(length):
        ai = (<DTYPE0_t*>(p + i * stride))[0]
        if ai == ai:
            asum += ai
            count += 1
    if count > 0:
        return asum / count
    else:
        return NAN
```
