### ISSUE TITLE
Speed up reduction along non fast axes

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#124]
For the C ordered array below Numpy is just as fast along axis 0 as it is along axis 1. Bottleneck is slow along axis 0.
```
In [1]: a = np.random.rand(1000, 10000)
In [2]: timeit np.nansum(a, 1)
10 loops, best of 3: 24.3 ms per loop
In [3]: timeit bn.nansum(a, 1)
100 loops, best of 3: 7.88 ms per loop
In [4]: timeit np.nansum(a, 0)
10 loops, best of 3: 24.8 ms per loop
In [5]: timeit bn.nansum(a, 0)
100 loops, best of 3: 16.1 ms per loop
```
I don't know how Numpy does it. But I imagine bottleneck could sum more than one column at a time using a temp C array. So instead of an `asum` variable we'd have an `asum[]` array and move along the fast axis (here axis 1) before advancing the slow axis (0).

Not sure how difficult it would be to implement.

**Comment by jennolsen84** [comment]
for a single threaded version, it seems not too bad as the "temp C array" is just the answer.  So, you're updating the answer all the time.

For the parallel case, one has to be a little bit more careful about `false sharing`, and make sure that the splitting of the work is along the cacheline.

**Comment by kwgoodman** [comment]
If we have a C ordered array with shape (100, 10000000) and we wish to sum along axis 0, then I worry that doing `output[i] += input[i]` along axis 1 will be just as bad, cache-wise, as the current implementation because output[i] is far away, memory-wise, from input[i]. So should I only do a few columns at a time to keep the range of i small? Probably makes the coding more difficult.

I don't understand your parallel warning. But if we ever get a working example we can test with multiple threads and look at performance.

**Comment by jennolsen84** [comment]
even if `output[i]` and `input[i]` are far, it should be ok*.  Since each array will only be using small part of the cache.  They should end up being in different cache lines.  Therefore, the simple implementation will work.

* The only exception to this is if they're exactly 4k multiple apart and map to the same cache line.  Then the performance will be terrible.
