### ISSUE TITLE
Where should we host the sphinx manual?

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#125]
I'd like to move the sphinx manual. Where should we host it? Github? Readthedocs?

**Comment by jennolsen84** [comment]
I prefer read the docs, but that's just a personal preference.  But not *everyone* knows about it, so perhaps both?

**Comment by kwgoodman** [comment]
OK, let's go with read the docs. I assume we need to make some changes to bn to prepare it for read the docs. Anyone out there want to make a PR?

**Comment by kwgoodman** [comment]
I decided against using readthedocs.org. They insert ads into the documentation. And there is no way to delete a user account (https://github.com/rtfd/readthedocs.org/issues/292).

I'll keep the docs where they are for now.

**Comment by shoyer** [comment]
Note that you can opt out of ads in RTD, though I find them pretty non-obtrusive:
http://blog.readthedocs.com/ads-on-read-the-docs/

**Comment by kwgoodman** [comment]
Good point. But I neither wanted ads nor wanted to opt out.

We'll see what happens when I have to renew my domain name and hosting. Bottleneck brings in $0. I'll probably be fine with ads once I have to cough up some cash.
