### ISSUE TITLE
consider splitting memory allocation and computation functions in the c_rewrite branch

### ISSUE THREAD

**Issue by jennolsen84** [kwgoodman/bottleneck#132]
e.g. see: https://github.com/kwgoodman/bottleneck/blob/6a4a315f7c5426b8071903697e5e65e27d0c905d/bottleneck/src/move2_template.c#L27 

If the split happens now, it will make it easy to parallelize these functions later.  Also, it makes it easy to benchmark the computation part only, as you can avoid repeated memory allocation.

**Comment by kwgoodman** [comment]
My plan was to do allocation of the output array in the mover function. That way the allocation is done in one place instead of duplicating the allocation code in every low-level function.

The problem was that mover does not currently know the dtype of the output array. We'd need to pass in a mapping of input dtype to output dtype. The mapping could be a C array like this
```
{NPY_FLOAT64, NPY_FLOAT32, NPY_FLOAT64, NPY_FLOAT64}
```
where it is understood that that four positions represent input arrays of type float64, float32, int64, int32. The mapping above is for move_mean.

It seemed messy so I wasn't sure that it was an improvement.

What did you have in mind for how to split?

**Comment by jennolsen84** [comment]
I didn't look too closely, but I wouldn't mind having the ability to pass in a buffer from outside bottleneck.

So, I wish I could do something like

`bn.move_mean(out = my_ndarray, ...)`

Then perhaps `bn.move_mean` would still check to make sure that the output argument matches exactly (dtype, shape, etc).  I am not sure if we should force the ordering though, but forcing dtype/shape/etc. makes some sense.

It would be nice to do this sooner than later, since it would make benchmarking things easier.  Right now, I have to modify the function a little bit before I can start benchmarking it.

And if we can get rid of all memory allocation, numpy interaction from the C implementation, perhaps other languages might want to integrate the C implementation.  Maybe Rust or Julia, but I am not that familiar with them.

**Comment by kwgoodman** [comment]
Can you explain the benchmarking comment? I don't understand.

**Comment by jennolsen84** [comment]
I guess, I should've said *profiling* instead of *benchmarking*

For profiling, I would like to isolate and analyze just the computation part.  Then make changes and examine the effect of that change.  With the current signature, we measure not just the hot loop, but the python memory allocation routines, etc.

So, what we can do is the move https://github.com/kwgoodman/bottleneck/blob/6a4a315f7c5426b8071903697e5e65e27d0c905d/bottleneck/src/move2_template.c#L27 line of code out of the INIT, and change the function signatures to pass in `y`.  Then I just wrote a separate C program that did not do memory allocation in the loop I used for benchmarking/profiling.

**Comment by kwgoodman** [comment]
I'd like to remove anything that needs the GIL from the low level functions. That includes the creation of the output array. But I might save it for bottleneck 1.3. Porting to C is a big project.

**Comment by kwgoodman** [comment]
Line-by-line profiling would help: #136.

**Comment by kwgoodman** [comment]
I'm closing this for now.
