### ISSUE TITLE
I'm considering switching to the GPL

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#133]
I prefer the GPL. I originally went with the BSD license because I saw that most numpy-based projects did so.

Recently I have spent a lot of time with bottleneck. Bottleneck 1.0 was a complete rewrite and bottleneck 1.2 will also be a complete rewrite. So I have had a chance to revisit most every decision I have ever made about bottleneck.

I know licensing can be contentious. So I thought I'd ask for comments before deciding (and before looking into whether I can legally make the change).

**Comment by shoyer** [comment]
I recommend against this, for the reasons described in [this article](http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/). It would mean that non-GPL projects such as pandas and xarray would need to stop using bottleneck or switch to using a fork instead.

**Comment by kwgoodman** [comment]
Hmm, so you're saying that even if bottleneck is optional to pandas and xarray you couldn't do something like:
```
try:
    from bottleneck import nansum
except:
    from numpy import nansum

nansum(a)
```

**Comment by shoyer** [comment]
Both xarray and pandas already have code that looks exactly like that. My
understanding of the intent of the GPL is to cover cases where the code is
merely imported. I'm not a lawyer, so instead of questioning that I simply
avoid GPL dependencies entirely. LGPL is a less viral option that would be
OK for a dependency.

**Comment by kwgoodman** [comment]
Because bottleneck is optional in pandas and xarray my guess is that the GPL would be OK. But a few minutes searching the web left me no examples. Yeah, so my guess isn't worth much.

I'm left with a choice between convenience and principal. And I'm embarrassed to say that I am leaning toward convenience. I'll keep bottleneck BSD but will give preference to the GPL for new projects.
