### ISSUE TITLE
Line-by-line profiling in C

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#136]
Does anyone know a way to do line-by-line profiling in C?

**Comment by Midnighter** [comment]
Have you tried [Cython profiling](http://docs.cython.org/en/latest/src/tutorial/profiling_tutorial.html#enabling-line-tracing)?

**Comment by kwgoodman** [comment]
The next release of bottleneck will drop Cython. And use C instead.

**Comment by Midnighter** [comment]
You could still use Cython to do profiling but maybe this [question on SO](https://stackoverflow.com/questions/9608949/gprof-time-spent-in-particular-lines-of-code) helps. [Here are some alternative programs](https://stackoverflow.com/questions/1777556/alternatives-to-gprof/1779343#1779343), personally I've used Valgrind before.
