### ISSUE TITLE
citation for bottleneck

### ISSUE THREAD

**Issue by jhamman** [kwgoodman/bottleneck#138]
@kwgoodman -

Do you have a preferred citation for bottleneck? We're citing this library in an overview paper of the xarray package.  Right now I have a generic bibtex of:

```
@manual{Bottleneck,
  author = {{Keith Goodman}},
  title = {Bottleneck: Fast NumPy array functions written in Cython},
  year = {2016},
  url = {https://github.com/kwgoodman/bottleneck}
}
```

[updated 2016-08-22]

**Comment by kwgoodman** [comment]
Neat.

I noticed that the other references in your bibtex don't have a period at the end of the title. So we can remove that. Can we change the url to https://github.com/kwgoodman/bottleneck? Or, if for some reason you don't like that one, https://pypi.python.org/pypi/Bottleneck?

It's nice to be referenced in a paper. Thank you.

**Comment by jhamman** [comment]
Thanks @kwgoodman!
