### ISSUE TITLE
Rename ss, partsort, and argpartsort?

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#139]
`ss` is now called `sum_of_squares` in scipy. Bottleneck should probably change the name as well.

Bottleneck's `partsort` and `argpartsort` were created before numpy had `partition` and `argpartition`. We should probably change those names as well. We'd also have to change the signature:

```
bn.partsort(arr, n, axis) == np.partition(arr, n - 1, axis)
```

Good idea?

**Comment by shoyer** [comment]
Yes!

**Comment by kwgoodman** [comment]
It's good to have a second opinion especially when changing the user API. Thanks.

I'll make the change sometime after merging the c_rewrite branch to master.

**Comment by kwgoodman** [comment]
Wait, instead of renaming `ss` to `sum_of_squares` it looks like scipy is deprecating it. From numpy master:
```
@np.deprecate(message="scipy.stats.ss is deprecated in scipy 0.17.0")
def ss(a, axis=0):
    return _sum_of_squares(a, axis)


def _sum_of_squares(a, axis=0):
    """
    Squares each element of the input array, and returns the sum(s) of that.
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int or None, optional
        Axis along which to calculate. Default is 0. If None, compute over
        the whole array `a`.
    Returns
    -------
    sum_of_squares : ndarray
        The sum along the given axis for (a**2).
    See also
    --------
    _square_of_sums : The square(s) of the sum(s) (the opposite of
    `_sum_of_squares`).
    """
    a, axis = _chk_asarray(a, axis)
    return np.sum(a*a, axis)
```

I'll keep the name `ss` for now.
