### ISSUE TITLE
package bottleneck 1.1.0 for debian

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#143]
@toobaz, do you plan to add bottleneck 1.1.0 to debian?

**Comment by toobaz** [comment]
Good question: yes I do... no I didn't! Busy period, but I hope to be able to work on it before end of the month. In case you want to proceed quicker, feel free to fork ``git://anonscm.debian.org/collab-maint/bottleneck.git`` , branch ``debian``.

**Comment by kwgoodman** [comment]
That's great news. It's nice being in Debian.

I'm working on bottleneck 1.2 at the moment. Before you package 1.1 you might want to check how close 1.2 is to being released---maybe I'll have an idea of when that is by then.

**Comment by toobaz** [comment]
OK: if you want me to upload 1.1, I will proceed this weekend. Otherwise I will wait for 1.2

**Comment by kwgoodman** [comment]
I don't know what the issues are (how long it would take 1.1 to clear sid, how much work etc). So I'll leave it to you.

Not sure when 1.2 will be released. Another few weeks?

**Comment by kwgoodman** [comment]
Bottleneck 1.2 is almost ready. So let's skip 1.1.

**Comment by kwgoodman** [comment]
See #153
