### ISSUE TITLE
Please help: osx10.11-xcode7.3 test failures?

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#150]
median and nanmedian are now failing on travis in bottleneck master. Travis [passed](https://travis-ci.org/kwgoodman/bottleneck/builds/164774403) and then after one commit (which only touched the AppVeyor files) it [failed](https://travis-ci.org/kwgoodman/bottleneck/builds/165096603).

I don't think the failures are related to the appveyor commit. Maybe related to a change in the osx builds? Help!

**Comment by kwgoodman** [comment]
From the log files mentioned above: Travis upgraded from osx10.9-xcode6.1 (bottleneck unit tests pass) to osx10.11-xcode7.3 (median, nanmedian fail).

**Comment by kwgoodman** [comment]
[Difference](https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live) between previous Xcode 6.1 image and current Xcode 7.3 image.

**Comment by kwgoodman** [comment]
I don't have osx so I added some printf statements and then looked at the results on Travis. Travis takes 15 to 20 minutes just to start a build on osx. So it has been painful. (Dealing with osx and windows, systems I don't use, is the most frustrating part of developing bottleneck.)

Adding printf statements got the unit tests to [pass](https://travis-ci.org/kwgoodman/bottleneck/jobs/165321786) but travis still says it is a failure. This message appears at the end of the [log](https://travis-ci.org/kwgoodman/bottleneck/jobs/165321786):
```
Ran 2 tests in 0.006s

OK

travis_nanoseconds

uname

travis_result $?

The command "source "tools/travis/bn_setup.sh"" exited with 0.

echo -e "\nDone. Your build exited with $TRAVIS_TEST_RESULT."

Done. Your build exited with 0.

travis_terminate $TRAVIS_TEST_RESULT

shell_session_update

/Users/travis/build.sh: line 109: shell_session_update: command not found
```

At this point I neither know what is causing the unit test failures or why `shell_session_update` isn't found.

**Comment by kwgoodman** [comment]
Does anyone have a computer with osx10.11-xcode7.3? If so, do the unit tests pass on bottleneck master?

**Comment by Midnighter** [comment]
Looks to be a common problem over at travis-ci, e.g., travis-ci/travis-ci#6307, travis-ci/travis-ci#6495, travis-ci/travis-ci#6522, and travis-ci/travis-ci#6677. A quick fix could be to force an older OS X image, i.e., put the following entry into the `matrix` of the `.travis.yml`:

```
osx_image: xcode6.4
```

**Comment by kwgoodman** [comment]
Yep, that [passes](https://travis-ci.org/kwgoodman/bottleneck/jobs/165377686). I read that the old xcode will only be around until the end of the month.

The big question for me is the unit test failures. Hopefully someone will test on their computer with osx10.11-xcode7.3.

I guess I'll hold the release of bottleneck 1.2 for a little while.

**Comment by kwgoodman** [comment]
We now know (e.g. PR #151) that bottleneck master works with osx10.9-xcode6.1 and osx10.10-xcode6.4. It does not appear to work with osx10.11-xcode7.3. But it would be nice if someone can confirm that.

**Comment by kwgoodman** [comment]
I guess I'll release bottleneck 1.2 without knowing if it runs on osx 10.11. No mac user has confirmed the bug or spoken up.

**Comment by jakirkham** [comment]
Is the only issue the `shell_session_update` error? That's just some Travis CI oddity that nobody seems to know how to solve.

xref: https://github.com/travis-ci/travis-ci/issues/6307
xref: https://github.com/travis-ci/travis-ci/issues/6495
xref: https://github.com/travis-ci/travis-ci/issues/6522

**Comment by kwgoodman** [comment]
I'm also seeing [unit test failures](https://travis-ci.org/kwgoodman/bottleneck/jobs/165096608) on osx10.11. Travis made a bunch of changes (e.g. the `shell_session_update` thing) so I was hoping that someone with osx 10.11 could tell us if the unit tests pass on the master branch.

**Comment by jakirkham** [comment]
If you have a script that you want me to run, I can run it tomorrow. Maybe longer if I need to cobble it together from source.

**Comment by kwgoodman** [comment]
There are a few different ways to run the test. Perhaps the most straightforward is to download the code:
```
https://github.com/kwgoodman/bottleneck/archive/master.zip
```
Then install it:
```
sudo python setup.py install
```
Then in python:
```
import bottleneck as bn
bn.test()
```

**Comment by jakirkham** [comment]
So I can confirm seeing all the same errors you saw on Travis CI on 10.11 with XCode 7.3.

**Comment by jakirkham** [comment]
Is there anything else you would like me to try?

**Comment by kwgoodman** [comment]
That's not the results I was hopping for :( But it is good to know.

Can you print the unit test failures? Something like this I would imagine:
```
Running unit tests for bottleneck

NumPy version 1.11.0

NumPy relaxed strides checking option: False

NumPy is installed in /Users/travis/miniconda/envs/test-python-3.4_64bit/lib/python3.4/site-packages/numpy

Python version 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:57) [GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]

nose version 1.3.7

FF

======================================================================

FAIL: test reduce functions

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/miniconda/envs/test-python-3.4_64bit/lib/python3.4/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/Users/travis/miniconda/envs/test-python-3.4_64bit/lib/python3.4/site-packages/bottleneck/tests/reduce_test.py", line 126, in unit_maker

    assert_array_almost_equal(actual, desired, decimal, err_msg)

  File "/Users/travis/miniconda/envs/test-python-3.4_64bit/lib/python3.4/site-packages/numpy/testing/utils.py", line 912, in assert_array_almost_equal

    precision=decimal)

  File "/Users/travis/miniconda/envs/test-python-3.4_64bit/lib/python3.4/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare

    raise AssertionError(msg)

AssertionError: 

Arrays are not almost equal to 5 decimals

func median | input a0 (int64) | shape (8,) | axis 0

Input array:

[7 5 1 6 0 2 4 3]

(mismatch 100.0%)

 x: array(2148493684.0)

 y: array(3.5)

======================================================================

FAIL: test reduce functions

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/miniconda/envs/test-python-3.4_64bit/lib/python3.4/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/Users/travis/miniconda/envs/test-python-3.4_64bit/lib/python3.4/site-packages/bottleneck/tests/reduce_test.py", line 126, in unit_maker

    assert_array_almost_equal(actual, desired, decimal, err_msg)

  File "/Users/travis/miniconda/envs/test-python-3.4_64bit/lib/python3.4/site-packages/numpy/testing/utils.py", line 912, in assert_array_almost_equal

    precision=decimal)

  File "/Users/travis/miniconda/envs/test-python-3.4_64bit/lib/python3.4/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare

    raise AssertionError(msg)

AssertionError: 

Arrays are not almost equal to 5 decimals

func nanmedian | input a0 (int64) | shape (8,) | axis 0

Input array:

[7 5 1 6 0 2 4 3]

(mismatch 100.0%)

 x: array(2148493684.0)

 y: array(3.5)

----------------------------------------------------------------------

Ran 2 tests in 0.005s

FAILED (failures=2)
```

**Comment by jakirkham** [comment]
I can, but can confirm that I already compared them to Travis CI and the errors were identical.

**Comment by kwgoodman** [comment]
osx 10.10 also fails if I use xcode 7.1 (but doesn't fail with xcode 6,4). So it seems to be related to xcode 7.

**Comment by kwgoodman** [comment]
`-std=c89` doesn't help

**Comment by kwgoodman** [comment]
I found it! 

I noticed that only slices with an even number of elements fail (median and nanmedian) on xcode 7.3. That narrowed down the lines of code where the problem could be. Turns out the problem is BN_INFINITY which is just NPY_INFINITY. Using gcc's INFINITY didn't solve things.

I don't yet know how to fix it. But at least I now know the problem.

Anybody have any ideas?

**Comment by kwgoodman** [comment]
I fixed the xcode 7 median, nanmedian bug. And added a workaround for the `shell_session_update` thing.

I don't understand why other functions, which also use BN_INFINITY, do not also have unit test failures with xcode 7. So I rewrote the entire bottleneck test suite to make it easier to see which functions are tested with infinity.
