### ISSUE TITLE
Compiling on Ubuntu 12.04

### ISSUE THREAD

**Issue by dieterv77** [kwgoodman/bottleneck#156]
I ran into a surprising issue when compiling bottleneck on Ubuntu 12.04.  Specifically, the problem seems to arise when there is one version of numpy installed in the system folders (for example, the one that ships with Ubuntu), but I override it by having a more recent version of numpy installed in my user folder (e.g. by installing numpy with the --user option of pip).

The problem seems to be that the python include folders include a link to the numpy include folder (which refers to the older version of numpy shipped with Ubuntu).   I was able to work around the problem by changing setup.py to do
self.include_dirs.insert(0, numpy.get_include())
instead of 
self.include.append(numpy.get_include())

This was based on some searching that led me to this commit in another project:
https://github.com/TRIQS/triqs/commit/d86c0df332874f71f3e82300b185d4a0d41e6831

Assuming this change is generally harmless (which i would imagine it is), then maybe setup.py can be changed moving forward?

Thanks very much for a great project!

**Comment by kwgoodman** [comment]
I never would have figured out how to fix the bug so thanks for the solution (and for the report). 

I applied your fix in the `issue_156` branch. Could you give it a try?

**Comment by dieterv77** [comment]
That seems to do the trick, i first tried compiling master (python setup.py build), and got the error i mentioned.  Then i switched to the branch and did the same thing and it compiled without any trouble.  I then actually installed that build and run the tests and all passed (this was with numpy 1.11.2).

So i think we're good to go.  Thanks very much

**Comment by kwgoodman** [comment]
Great. I'll merge.
