### ISSUE TITLE
Error on Install 

### ISSUE THREAD

**Issue by syntaxc** [kwgoodman/bottleneck#165]
$ sudo pip install bottleneck
Collecting bottleneck
  Using cached Bottleneck-1.2.0.tar.gz
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from bottleneck)
Installing collected packages: bottleneck
  Running setup.py install for bottleneck ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o452GJ/bottleneck/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-SKvTfk-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/bottleneck
    copying bottleneck/version.py -> build/lib.linux-x86_64-2.7/bottleneck
    copying bottleneck/__init__.py -> build/lib.linux-x86_64-2.7/bottleneck
    creating build/lib.linux-x86_64-2.7/bottleneck/tests
    copying bottleneck/tests/util.py -> build/lib.linux-x86_64-2.7/bottleneck/tests
    copying bottleneck/tests/list_input_test.py -> build/lib.linux-x86_64-2.7/bottleneck/tests
    copying bottleneck/tests/move_test.py -> build/lib.linux-x86_64-2.7/bottleneck/tests
    copying bottleneck/tests/reduce_test.py -> build/lib.linux-x86_64-2.7/bottleneck/tests
    copying bottleneck/tests/__init__.py -> build/lib.linux-x86_64-2.7/bottleneck/tests
    copying bottleneck/tests/scalar_input_test.py -> build/lib.linux-x86_64-2.7/bottleneck/tests
    copying bottleneck/tests/nonreduce_axis_test.py -> build/lib.linux-x86_64-2.7/bottleneck/tests
    copying bottleneck/tests/input_modifcation_test.py -> build/lib.linux-x86_64-2.7/bottleneck/tests
    copying bottleneck/tests/nonreduce_test.py -> build/lib.linux-x86_64-2.7/bottleneck/tests
    creating build/lib.linux-x86_64-2.7/bottleneck/benchmark
    copying bottleneck/benchmark/bench_detailed.py -> build/lib.linux-x86_64-2.7/bottleneck/benchmark
    copying bottleneck/benchmark/autotimeit.py -> build/lib.linux-x86_64-2.7/bottleneck/benchmark
    copying bottleneck/benchmark/bench.py -> build/lib.linux-x86_64-2.7/bottleneck/benchmark
    copying bottleneck/benchmark/__init__.py -> build/lib.linux-x86_64-2.7/bottleneck/benchmark
    creating build/lib.linux-x86_64-2.7/bottleneck/slow
    copying bottleneck/slow/nonreduce.py -> build/lib.linux-x86_64-2.7/bottleneck/slow
    copying bottleneck/slow/__init__.py -> build/lib.linux-x86_64-2.7/bottleneck/slow
    copying bottleneck/slow/move.py -> build/lib.linux-x86_64-2.7/bottleneck/slow
    copying bottleneck/slow/nonreduce_axis.py -> build/lib.linux-x86_64-2.7/bottleneck/slow
    copying bottleneck/slow/reduce.py -> build/lib.linux-x86_64-2.7/bottleneck/slow
    creating build/lib.linux-x86_64-2.7/bottleneck/src
    copying bottleneck/src/template.py -> build/lib.linux-x86_64-2.7/bottleneck/src
    copying bottleneck/src/__init__.py -> build/lib.linux-x86_64-2.7/bottleneck/src
    copying bottleneck/LICENSE -> build/lib.linux-x86_64-2.7/bottleneck
    running build_ext
    building 'bottleneck.reduce' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/bottleneck
    creating build/temp.linux-x86_64-2.7/bottleneck/src
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -c bottleneck/src/reduce.c -o build/temp.linux-x86_64-2.7/bottleneck/src/reduce.o -O2
    In file included from bottleneck/src/reduce.c:2:0:
    bottleneck/src/iterators.h: In function ‘init_iter_one’:
    bottleneck/src/iterators.h:32:5: warning: implicit declaration of function ‘PyArray_SHAPE’ [-Wimplicit-function-declaration]
    bottleneck/src/iterators.h:32:29: warning: initialization makes pointer from integer without a cast [enabled by default]
    bottleneck/src/iterators.h: In function ‘init_iter_all’:
    bottleneck/src/iterators.h:67:29: warning: initialization makes pointer from integer without a cast [enabled by default]
    bottleneck/src/iterators.h:84:14: error: ‘NPY_ARRAY_C_CONTIGUOUS’ undeclared (first use in this function)
    bottleneck/src/iterators.h:84:14: note: each undeclared identifier is reported only once for each function it appears in
    bottleneck/src/iterators.h:90:14: error: ‘NPY_ARRAY_F_CONTIGUOUS’ undeclared (first use in this function)
    bottleneck/src/iterators.h: In function ‘init_iter2’:
    bottleneck/src/iterators.h:181:29: warning: initialization makes pointer from integer without a cast [enabled by default]
    bottleneck/src/iterators.h: In function ‘init_iter3’:
    bottleneck/src/iterators.h:258:29: warning: initialization makes pointer from integer without a cast [enabled by default]
    error: command 'gcc' failed with exit status 1

**Comment by itdaniher** [comment]
Looks like you might be missing numpy headers? How'd you install numpy?

**Comment by syntaxc** [comment]
I installed numpy using pip.

**Comment by itdaniher** [comment]
same virtualenv / same user?

**Comment by syntaxc** [comment]
It looks like the numpy headers files are in:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy

I'm not using a virtualenv.
All commands are being run as root.

**Comment by syntaxc** [comment]
Solved.
Numpy was originally installed via apt-get, then upgrade through pip.

Old numpy headers were left in: /usr/include/python2.7/numpy
I deleted the directory and the installer started using the proper headers.

Thank you for your help (and so quickly!)

**Comment by kwgoodman** [comment]
My favorite kind of issue---solved before I read it.

**Comment by itdaniher** [comment]
:) happy to help!
