### ISSUE TITLE
upgrading bottleneck to numpy 1.12.1

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#166]
I upgraded bottleneck to numpy 1.12.1 but then ran into [this problem on appveyor:](https://ci.appveyor.com/project/kwgoodman/bottleneck/build/%2371/job/8polwkejk55vh2o7)
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.12.1* -> python 2.7*
  - python 3.4*
Use "conda info <package>" to see the dependencies for each package.
```
Any ideas?

**Comment by kwgoodman** [comment]
Ack! I see [the same issue on linux, osx](https://travis-ci.org/kwgoodman/bottleneck/builds/218219800), and windows. It's only for python 3.4

**Comment by shoyer** [comment]
They don't build packages on main conda channel for Python 3.4. But the conda-forge channel does. Try adding `-c conda-forge` to your `conda create` commands.

**Comment by kwgoodman** [comment]
I switched to testing bottleneck with py 2.7, 3.5, 3.6 instead of py 2.7, 3.4, 3.5.
