### ISSUE TITLE
 'NAN' undeclared @ bottleneck/src/move_median/move_median.c:522

### ISSUE THREAD

**Issue by kevinyuan** [kwgoodman/bottleneck#167]
----------------------------------------
  Failed building wheel for bottleneck
  Running setup.py clean for bottleneck
Failed to build bottleneck
Installing collected packages: bottleneck
  Running setup.py install for bottleneck ... error
    Complete output from command /home-tahoe-n2/kevinyuan/dev/zipline/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q45ln91e/bottleneck/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0mwwsdih-record/install-record.txt --single-version-externally-managed --compile --install-headers /home-tahoe-n2/kevinyuan/dev/zipline/include/site/python3.5/bottleneck:
    running install
    running build
    running build_py
    running build_ext
    building 'bottleneck.reduce' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/bottleneck
    creating build/temp.linux-x86_64-3.5/bottleneck/src
    /share/dev/tools/bin/gcc493 -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/share/dev/tools/include/python3.5m -I/home-tahoe-n2/kevinyuan/dev/zipline/lib/python3.5/site-packages/numpy/core/include -c bottleneck/src/reduce.c -o build/temp.linux-x86_64-3.5/bottleneck/src/reduce.o -O2
    /share/dev/tools/bin/gcc493 -pthread -shared build/temp.linux-x86_64-3.5/bottleneck/src/reduce.o -o build/lib.linux-x86_64-3.5/bottleneck/reduce.cpython-35m-i386-linux-gnu.so
    building 'bottleneck.move' extension
    creating build/temp.linux-x86_64-3.5/bottleneck/src/move_median
    /share/dev/tools/bin/gcc493 -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/share/dev/tools/include/python3.5m -I/home-tahoe-n2/kevinyuan/dev/zipline/lib/python3.5/site-packages/numpy/core/include -c bottleneck/src/move.c -o build/temp.linux-x86_64-3.5/bottleneck/src/move.o -O2
    /share/dev/tools/bin/gcc493 -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/share/dev/tools/include/python3.5m -I/home-tahoe-n2/kevinyuan/dev/zipline/lib/python3.5/site-packages/numpy/core/include -c bottleneck/src/move_median/move_median.c -o build/temp.linux-x86_64-3.5/bottleneck/src/move_median/move_median.o -O2
    bottleneck/src/move_median/move_median.c: In function 'mm_get_median':
    bottleneck/src/move_median/move_median.c:522:16: error: 'NAN' undeclared (first use in this function)
             return NAN;
                    ^
    bottleneck/src/move_median/move_median.c:522:16: note: each undeclared identifier is reported only once for each function it appears in
    error: command '/share/dev/tools/bin/gcc493' failed with exit status 1

    ----------------------------------------
Command "/home-tahoe-n2/kevinyuan/dev/zipline/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q45ln91e/bottleneck/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0mwwsdih-record/install-record.txt --single-version-externally-managed --compile --install-headers /home-tahoe-n2/kevinyuan/dev/zipline/include/site/python3.5/bottleneck" failed with error code 1 in /tmp/pip-build-q45ln91e/bottleneck/

**Comment by kwgoodman** [comment]
Can you try with the lastest from bottleneck master?

**Comment by kevinyuan** [comment]
Hi kwgoodman,

Yes it passed the compile.

Previously I installed it from "pip install bottleneck" but it failed.

Not sure if it's a packaging problem.

Thanks.

**Comment by kwgoodman** [comment]
Good. Then the new release #168 should work. If the unit tests pass (or if they don't) you can report it and your OS to #168.
