### ISSUE TITLE
Drop the vendored copy of numpydoc

### ISSUE THREAD

**Issue by ghisvail** [kwgoodman/bottleneck#171]
Please consider dropping the vendored copy of `numpydoc` in favor of adding an `extra_requires` to your setuptools metadata.

**Comment by kwgoodman** [comment]
Sounds like a good idea. I assume most people don't build the docs. Is there a way to require numydoc only if the docs are built?

**Comment by ghisvail** [comment]
```python
extra_requires = {'doc': ['sphinx', 'numpydoc']}
```

**Comment by kwgoodman** [comment]
If I remove numpydoc from bottleneck and add the extra_requires line and then run `python setup.py install`, numpydoc is not installed.

Maybe I'll remove numpydoc and just list (in readme) sphinx and numpydoc as requirements for building the docs. Does that sounds OK?

**Comment by ghisvail** [comment]
> run python setup.py install, numpydoc is not installed.

Which is to expected. `numpydoc` is not an install dependency afterall so this is an appropriate behavior.

You can run `pip install -e .[doc]` to get the extra dependencies associated to `doc` installed.

**Comment by kwgoodman** [comment]
bottleneck also uses nose. Do you think it is OK not to have an extra_requires and just list the optional dependencies in the readme?

**Comment by ghisvail** [comment]
Your call. As long as it is made explicit somewhere, it's fine.

**Comment by kwgoodman** [comment]
Great idea to remove numpydoc. Thanks.
