### ISSUE TITLE
Domain name for site hosting docs expired

### ISSUE THREAD

**Issue by delgadom** [kwgoodman/bottleneck#172]
The [Berkeley Analytics](http://berkeleyanalytics.com/bottleneck) site is down - currently there is a GoDaddy splash page instead. Any chance the site could be renewed or better yet the docs could be hosted on rtd?

**Comment by kwgoodman** [comment]
I tried github pages: https://kwgoodman.github.io/bottleneck-doc

Any know how to recover the sphinx theme?

**Comment by kwgoodman** [comment]
Formatting fixed. Bottleneck docs are now at https://kwgoodman.github.io/bottleneck-doc

Thanks for the report @delgadom
