### ISSUE TITLE
License lists full history of Python licenses instead of relevant PSF license.

### ISSUE THREAD

**Issue by DanHakimi** [kwgoodman/bottleneck#174]
Under setuptools in your license, you list, correctly, that setuptools is dual-licensed. Then, you copy and paste in both licenses. But instead of copying the PSF license, it appears you copied the entire history of licenses that python has used in the past, and which pieces of python use, as seen here https://docs.python.org/3/license.html. I believe that setuptools' license specifically refers to the PSF license, and does not invoke every license in Python's history.

**Comment by kwgoodman** [comment]
Would be great if we can make the package smaller by removed superfluous stuff. I don't really understand the issues involved. Would you, or anyone else out there, care to make a pull request? Or a comment on the issue.

**Comment by DanHakimi** [comment]
Sorry it took me so long to take care of this -- how's that?

**Comment by kwgoodman** [comment]
Looks good. Can you make a pull request off of https://github.com/DanHakimi/bottleneck/commit/22ccb8ca435d26d5c0277b598badd84b93928acd?

**Comment by DanHakimi** [comment]
Oh, uh, sorry, I was just using the github web ui for that, and I thought it was supposed to send the pull request automatically... I think I just submitted it, did that work?

**Comment by kwgoodman** [comment]
After you submit it it will show up here https://github.com/kwgoodman/bottleneck/pulls

**Comment by DanHakimi** [comment]
Alright, I am trying to figure this out with Github Support, but essentially, I'm trying to hit "new pull request" and put in that commit's id number, but I get to a page comparing changes between branches with no option to actually submit the pull request. I feel like I should know how to do this by now... Sorry for my incompetence!

**Comment by kwgoodman** [comment]
Thank you!
