### ISSUE TITLE
bench fails on python 3.6.3

### ISSUE THREAD

**Issue by gwin-zegal** [kwgoodman/bottleneck#175]
With python 3.6.3 (build from conda, mac OS), an error occurred during bn performance benchmark.

<pre><code>import bottleneck as bn
bn.bench()</code></pre>

log:

<pre><code>Bottleneck performance benchmark
    Bottleneck 1.2.1; Numpy 1.13.3
    Speed is NumPy time divided by Bottleneck time
    NaN means approx one-fifth NaNs; float64 used

              no NaN     no NaN      NaN       no NaN      NaN    
               (100,)  (1000,1000)(1000,1000)(1000,1000)(1000,1000)
               axis=0     axis=0     axis=0     axis=1     axis=1  
nansum         32.8        1.2        2.0        2.5        3.9
nanmean       119.4        1.6        1.7        4.9        3.3
nanstd        200.1        1.7        1.8        5.6        3.7
nanvar        186.9        1.7        1.8        5.7        3.6
nanmin         30.0        0.4        0.4        1.0        1.1
nanmax         30.4        0.4        0.4        1.0        1.0
median         89.1        1.8        4.1        1.6        6.4
nanmedian      84.0        7.1        6.7        6.8        7.9
ss             22.0        1.3        1.3        5.0        4.9
nanargmin      59.2        2.6        3.2        3.1        4.9
nanargmax      62.9        2.6        3.4        3.1        4.4
anynan         18.0        0.3       89.4        1.2       68.1
allnan         23.7      382.6      232.7      301.8      146.7
rankdata       36.2        2.0        2.0        2.7        2.8
nanrankdata    38.4        2.3        2.1        3.2        3.1
Traceback (most recent call last):
  File "bn.py", line 2, in <module>
    bn.bench()
  File "/Users/manu/Documents/Developpement/python/anaconda/current/lib/python3.6/site-packages/bottleneck/benchmark/bench.py", line 77, in bench
    speed = timer(test['statements'], test['setups'])
  File "/Users/manu/Documents/Developpement/python/anaconda/current/lib/python3.6/site-packages/bottleneck/benchmark/bench.py", line 87, in timer
    t0 = autotimeit(statements[0], setup)
  File "/Users/manu/Documents/Developpement/python/anaconda/current/lib/python3.6/site-packages/bottleneck/benchmark/autotimeit.py", line 7, in autotimeit
    number, time1 = autoscaler(timer, mintime)
  File "/Users/manu/Documents/Developpement/python/anaconda/current/lib/python3.6/site-packages/bottleneck/benchmark/autotimeit.py", line 15, in autoscaler
    time = timer.timeit(number)
  File "/Users/manu/Documents/Developpement/python/anaconda/current/lib/python3.6/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 16, in inner
TypeError: `n` must be an integer</code></pre>

**Comment by kwgoodman** [comment]
Thank you for the report! I think I fixed it. Could you give it a try (it's in master)?

**Comment by gwin-zegal** [comment]
That did it! Thank you.
For information, here the bench result on an old machine with a <code>Intel(R) Core(TM)2 Duo CPU     P8700  @ 2.53GHz</code> (macbook 2009)

<pre><code>Bottleneck performance benchmark
    Bottleneck 1.2.1; Numpy 1.13.3
    Speed is NumPy time divided by Bottleneck time
    NaN means approx one-fifth NaNs; float64 used

              no NaN     no NaN      NaN       no NaN      NaN    
               (100,)  (1000,1000)(1000,1000)(1000,1000)(1000,1000)
               axis=0     axis=0     axis=0     axis=1     axis=1  
nansum         32.7        1.2        1.9        2.4        4.0
nanmean       118.5        1.6        1.7        4.9        3.4
nanstd        195.8        1.7        1.8        5.7        3.7
nanvar        185.5        1.7        1.8        5.7        3.6
nanmin         29.4        0.4        0.4        1.1        1.1
nanmax         29.0        0.4        0.4        1.0        1.0
median         94.7        1.8        4.2        1.5        6.3
nanmedian      82.9        5.7        6.2        6.6        7.8
ss             22.4        1.3        1.3        5.0        5.0
nanargmin      60.5        2.6        3.1        3.1        5.1
nanargmax      63.5        2.5        3.1        3.0        4.7
anynan         18.7        0.3       89.4        1.2       73.3
allnan         24.2      392.2      235.3      224.3      149.7
rankdata       36.2        2.1        2.1        2.7        2.8
nanrankdata    38.7        2.2        2.1        3.0        3.1
partition       3.7        1.1        1.3        1.0        1.2
argpartition    3.5        1.0        1.1        1.0        1.3
replace        10.1        1.8        1.8        1.8        1.8
push         2198.8        4.3        5.5       10.5       10.7
move_sum     3477.6       82.4      114.8      273.3      294.3
move_mean    7908.2       95.9      126.3      267.4      239.5
move_std    10092.4      125.9      156.8      220.5      197.8
move_var    10951.4      132.6      170.9      262.2      263.3
move_min     1516.9       18.8       17.6       44.0       41.5
move_max     1404.3       17.6       16.9       38.1       37.2
move_argmin  2149.7       99.6      117.9       84.9      122.6
move_argmax  2197.0       97.1      119.6       84.9      121.6
move_median  1377.7      204.1      211.8      191.2      193.1
move_rank     640.6        2.1        2.0        2.8        2.8</code></pre>
