### ISSUE TITLE
Error when passing in a default to bn.push

### ISSUE THREAD

**Issue by MaximilianR** [kwgoodman/bottleneck#178]
Bottleneck doesn't seem to be well behaved if you _pass in_ default values for `bn.push`:

Default states `n=None` (and works with no value):

python
```
In [1]: import bottleneck as bn

In [4]: import numpy as np

In [5]: a=np.array([1,2,3,4])

In [7]: bn.push(a)
Out[7]: array([1, 2, 3, 4])

In [8]: bn.push?
Docstring:
push(a, n=None, axis=-1)
...
n : {int, None}, optional
```

but when you pass in `None`, it raises:
```
In [9]: bn.push(a, n=None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-d7ea6fc52366> in <module>()
----> 1 bn.push(a, n=None)

TypeError: `n` must be an integer
```

This is only really impactful when building a function that uses `bottleneck`, (which we're increasingly doing in `xarray`)

**Comment by kwgoodman** [comment]
Thanks for the bug report.

OK, some notes for reference either for me when I get to it or someone else if they'd like to give a try making a PR.

First make failing unit test.

Then special case push here where n_obj is parsed:
```
    /* ddof */
    if (n_obj == NULL) {
        n = -1;
    }
    else {
        n = PyArray_PyIntAsInt(n_obj);
        if (error_converting(n)) {
            TYPE_ERR("`n` must be an integer");
            return NULL;
        }
        if (n < 0 && parse == PARSE_PUSH) {
            VALUE_ERR("`n` must be nonnegative");
            return NULL;
        }
    }
```
From how the parsing of axis_obj is handled you get the idea of how to special case.

**Comment by kwgoodman** [comment]
OK, I fixed it. It's in master. Give it a try.

**Comment by MaximilianR** [comment]
That's fast - thank you!
