### ISSUE TITLE
Provide compiled package

### ISSUE THREAD

**Issue by yhvh** [kwgoodman/bottleneck#179]
Adding a compiled package would decrease install times.

https://www.python.org/dev/peps/pep-0513/
https://github.com/pypa/manylinux
https://github.com/pypa/python-manylinux-demo

**Comment by kwgoodman** [comment]
It's a good idea but I am trying to keep maintenance costs low.

Takes 5 seconds to compile on my computer. But of course that's only because I already have the dependencies installed. There are binaries in several linux distributions.

**Comment by AllanLRH** [comment]
Have a look at conda forge, you might be able to find Bottleneck there.
