### ISSUE TITLE
bn.nansum on boolean array

### ISSUE THREAD

**Issue by TomAugspurger** [kwgoodman/bottleneck#180]
Is this behavior expected?

```python
In [1]: import numpy as np

In [2]: import bottleneck as bn

In [3]: arr = np.array([True, True, False])

In [4]: np.nansum(arr)  # cast from bool -> int
Out[4]: 2

In [5]: bn.nansum(arr)  # no upcasting
Out[5]: True
```

I'm not sure what bottleneck's goals are are w.r.t upcasting output types.

**Comment by kwgoodman** [comment]
The C code in bottleneck is only called for int32, int64, float32, float64. Everything else goes to the corresponding python version of the function. In this case: bn.slow.nansum.

Unlike numpy, bn.nansum doesn't return int64 when input is int32. That explains the if statement in bn.slow.nansum.

**Comment by kwgoodman** [comment]
@TomAugspurger I pushed a fix to master:
```
In [1]: bn.nansum([True, True, False])
Out[1]: 2
In [2]: bn.ss([True, True, False])
Out[2]: 2
```

**Comment by TomAugspurger** [comment]
Thanks!
