### ISSUE TITLE
bn.nansum on array with np.newaxis added dimension 

### ISSUE THREAD

**Issue by ng0** [kwgoodman/bottleneck#183]
Bottleneck's nansum (and nanmean, etc) doesn't seem to give the right answer when dimensions are added with np.newaxis. An example is:

In [27]: a = np.ones((2,2))

In [28]: a[1, :] = np.nan

In [29]: bn.nansum(a) # Correct
Out[29]: 2.0

In [30]: bn.nansum(a[..., np.newaxis])  # **Wrong**
Out[30]: 4.0

In [31]: np.nansum(a[..., np.newaxis])  # numpy does the right thing.
Out[31]: 2.0

In [32]: np.__version__
Out[32]: '1.12.1'

In [33]: bn.__version__
Out[33]: '1.2.1'

**Comment by kwgoodman** [comment]
That is a big bug! Thank you so much for reporting it!

I can reproduce it:
```
In [1]: a = np.array([[1, 2],[3, 4.0]])
In [2]: bn.nansum(a)
ai=1.000000 i=0 astride=8
ai=2.000000 i=1 astride=8
ai=3.000000 i=2 astride=8
ai=4.000000 i=3 astride=8
Out[2]: 10.0
In [3]: bn.nansum(a[...,np.newaxis])
ai=1.000000 i=0 astride=0
ai=1.000000 i=1 astride=0
ai=1.000000 i=2 astride=0
ai=1.000000 i=3 astride=0
Out[3]: 4.0
In [4]: a[...,np.newaxis].strides
Out[4]: (16, 8, 0)
```
Problems also occurs with F ordered array:
```
In [5]: a = np.array(a, order='F')
In [6]: bn.nansum(a[...,np.newaxis])
ai=1.000000 i=0 astride=8
ai=3.000000 i=1 astride=8
ai=2.000000 i=2 astride=8
ai=4.000000 i=3 astride=8
Out[6]: 10.0
In [7]: bn.nansum(a[np.newaxis, ...])
ai=1.000000 i=0 astride=0
ai=1.000000 i=1 astride=0
ai=1.000000 i=2 astride=0
ai=1.000000 i=3 astride=0
Out[7]: 4.0
```
And problem occurs with other functions besides nansum.

Bug is in this code which was recently added to deal with relaxed strides checking in numpy:
```
    /* The &&! in the next two else ifs is to deal with relaxed
     * stride checking introduced in numpy 1.12.0; see gh #161 */
    else if (C_CONTIGUOUS(a) && !F_CONTIGUOUS(a)) {
        it->ndim_m2 = -1;
        it->axis = ndim - 1;
        it->length = PyArray_SIZE(a);
        it->astride = strides[ndim - 1];
    }
    else if (F_CONTIGUOUS(a) && !C_CONTIGUOUS(a)) {
        if (anyorder || !ravel) {
            it->ndim_m2 = -1;
            it->length = PyArray_SIZE(a);
            it->astride = strides[0];
        } else {
            it->ndim_m2 = -1;
            if (anyorder) {
                a = (PyArrayObject *)PyArray_Ravel(a, NPY_ANYORDER);
            } else {
                a = (PyArrayObject *)PyArray_Ravel(a, NPY_CORDER);
            }
            it->a_ravel = a;
            it->length = PyArray_DIM(a, 0);
            it->astride = PyArray_STRIDE(a, 0);
        }
    }
```
It was a hack but since my unit tests passed...

I'm guessing I can just look for the first axis (from the end for C ordered) that has a zero stride.

**Comment by kwgoodman** [comment]
I pushed a fix to master. If you give it a try, let me know if it works for you.

**Comment by ng0** [comment]
Hi, thanks for turning this around so quickly. I have tested your patch and it seems to work for me, at least in the cases I could think of testing.

**Comment by kwgoodman** [comment]
Great. Thanks for testing.
