### ISSUE TITLE
Speed up anynan for float32 and float64 using isunordered

### ISSUE THREAD

**Issue by jzwinck** [kwgoodman/bottleneck#197]
The C function `isunordered(x, y)` returns 1 if either argument is NAN.  This can be used to check two values per `anynan()` loop iteration instead of one.

How to implement this is not so clear to me due to the [macros involved](https://github.com/kwgoodman/bottleneck/blob/f783ce7a53a3375cd5c3e5c943c098b21254eb96/bottleneck/src/reduce_template.c#L948), but I did verify that `anynan_all_float64()` generates code using `ucomisd %xmm0 %xmm0`.  If bottleneck would "unroll" the loop 2x by calling `isunordered()`, the generated code should be `ucomisd %xmm0 %xmm1` or similar, and the loop iterations would be cut in half.

**Comment by kwgoodman** [comment]
Sounds interesting. The anynan function short circuits and exits as soon as a nan is found. But for the case where there are no nans the entire array must be checked. The fastest nan check I have found so far is `x != x`. And of course we can unroll the loop with `x != x` too. So I'd only look at `isunordered` if it is faster than two `x != x` checks without loop unrolling.

**Comment by kwgoodman** [comment]
oh, and if the two array elements have to be passed to a single function then I assume we can't unroll the loop in the way you suggest?
