### ISSUE TITLE
Add move_percentile()

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#30]
Add a moving window scoreatpercentile function. It could be based on the move_median code with some slight modifications.

**Comment by ThomasLecocq** [comment]
:+1:  is this complicated to implement ?

**Comment by kwgoodman** [comment]
My four year old comment makes it sound easy. But you know how that goes. The move_median code is the most complicated code in bottleneck. And I'm not too excited about using it as the basis of other function until it can handle NaNs.

It is already a scoreatpercentile function if you want the score at the 50th percentile. You could hack something together to move the 50th percentile. If you do, let us know how it goes.

**Comment by kwgoodman** [comment]
bn.move_median now supports NaNs and min_count. So we are in good shape to add a move_percentile function.
