### ISSUE TITLE
Cannot build/install on Ubuntu 12.10 64Bit in Virtual Machine

### ISSUE THREAD

**Issue by stefanocrosta** [kwgoodman/bottleneck#54]
Hello,

I'm not pretending that somebody will track down the cause but I thought I'd share the situation.

I'm trying to install bottleneck on a VirtualBox 64bits Ubuntu 12.10 guest.

>  python setup.py install

ends with the following lines:

```
bottleneck/src/func/64bit/func.c: At top level:
/home/scrosta/virtualenv/local/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
error: command 'gcc' failed with exit status 4
```

where of course the `gcc: internal compiler error: Killed (program cc1)` is the ugly bit.

Also when trying a `make all` from the repository gives exactly the same error:

```
/home/scrosta/virtualenv/local/lib/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:226:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
error: command 'gcc' failed with exit status 4
make: *** [funcs] Error 1
```

**Comment by kwgoodman** [comment]
@stefanocrosta, I have rewritten bottleneck. I'm curious if it now builds on a VM, so if you get a chance to try, let me know.

**Comment by stefanocrosta** [comment]
Hello @kwgoodman yes now it does, no more errors!
(it's a different VM though... my older laptop retired...)

thanks!!

**Comment by kwgoodman** [comment]
That's great! Thanks.
