### ISSUE TITLE
bottleneck installation with pip doesn't work if numpy is not already installed

### ISSUE THREAD

**Issue by lebedov** [kwgoodman/bottleneck#78]
Although bottleneck does specify numpy as a PEP 345-type requirement, this is insufficient to have numpy automatically installed when bottleneck is installed via pip. This complicates the installation of other Python packages via pip that use setuptools (or distribute) and specify bottleneck as a dependency. Would it be possible to update bottleneck to use setuptools/distribute rather than distutils for installation? If so, I would be happy to contribute an updated setup.py.

**Comment by kwgoodman** [comment]
@lebedov, if you have time could you retest master with pip? I have completely rewritten bottleneck and am afraid I might have broken something.

**Comment by lebedov** [comment]
I was able to successfully install master directly from GitHub in a fresh Python 2.7 virtualenv using pip; numpy was automatically downloaded and built.

**Comment by lebedov** [comment]
All tests on the installed code run successfully too.

**Comment by kwgoodman** [comment]
Thanks, Lev.
