### ISSUE TITLE
Unifying Cython code for different axes with swapaxes

### ISSUE THREAD

**Issue by shoyer** [kwgoodman/bottleneck#87]
Following up on #86, I would like to use `np.swapaxes` (`np.transpose` more generally) so that we can remove the redundant Cython code for different axes.

For a function like `bottleneck.nansum`, this should be straightforward. I can insert a call to `np.swapaxes` in `nansum_selector` to always switch the array so it should summed over `axis=-1`, and then none of the API needs to change.

But the design is a little trickier for functions that don't remove a dimension (e.g., all the moving window functions). For these functions, we'll need to call `np.swapaxes` after performing the operation along a fixed axis. To maintain the current selector API, I could either:

1. Write a bunch of wrapper functions (similar to `move_nansum_slow_axis0`) for each combination of axis, dtype and ndim, and include them in the Cython source code. This is not ideal, although I suppose it is still an improvement over what currently exists.
2. Generate the wrapper function dynamically, when calling `move_nansum_selector`. This would be my preferred approach if I were writing pure Python, but I'm not sure how Cython changes things.

Thoughts?

**Comment by kwgoodman** [comment]
The rewrite of bottleneck took care of this issue.
