### ISSUE TITLE
Typed memoryviews

### ISSUE THREAD

**Issue by u0078867** [kwgoodman/bottleneck#89]
Hi,

first of all, thanks for the great tool!

Was wondering if it would make sense to turn the standard buffer syntax into typed memoryviews, since I have read they are considerably faster, They way they are declared makes them certainly less parameterizable in terms of dimensions number.

Cheers!
Davide

**Comment by kwgoodman** [comment]
While rewriting bottleneck I tried memoryviews. But I found that pointers worked better for me. So I went with pointers.
