### ISSUE TITLE
Monkeypatch NumPy

### ISSUE THREAD

**Issue by thedrow** [kwgoodman/bottleneck#90]
Can bottleneck monkeypatch NumPy so that libraries that uses it such as scikit-learn (or any other scikit) will use the specialized bottleneck versions whenever it is applicable?
Is it possible? If not, I will take it upstream and ask scikit-learn to use bottleneck where applicable.

**Comment by kwgoodman** [comment]
I'm going to close this simply because I don't understand it. Feel free to reopen if you have an example and/or if multiple people think it is a good idea.

**Comment by kernc** [comment]
Another vote for this good idea!

Would a pull request be considered?

**Comment by anntzer** [comment]
+1 for supporting monkey patching.

A similar case is pyfftw, which is also an accelarator module for numpy/scipy.  See https://hgomersall.github.io/pyFFTW/sphinx/tutorial.html#monkey-patching-3rd-party-libraries, which gives proposes
```
# Monkey patch fftpack with pyfftw.interfaces.scipy_fftpack
scipy.fftpack = pyfftw.interfaces.scipy_fftpack
```
(although there the patching occurs at module level).
