### ISSUE TITLE
Rewrite of bottleneck internals

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#92]
Here's a proposal for a rewrite of the bottlleneck internals. The main goals:

- Easier to add functions to bottleneck
- Easier to maintain
- Less C code

The easiest way to explain what I have in mind is with an example written in pure python:

```
import numpy as np


def nanmean_2d_float64_axis0(a):
    algo = Nanmean()
    return reduce_2d_float64_axis0(a, algo)


def reduce_2d_float64_axis0(a, algo):
    n0, n1 = a.shape
    y = np.empty(n1)
    for j in range(n1):
        algo.clear()
        for i in range(n0):
            ai = a[i, j]
            algo.append(ai)
        y[j] = algo.calc()
    return y


class Nanmean(object):

    def __init__(self):
        self.count = 0
        self.asum = 0

    def append(self, ai):
        if ai == ai:
            self.asum += ai
            self.count += 1

    def calc(self):
        if self.count > 0:
            return self.asum / self.count
        else:
            return np.nan

    def clear(self):
        self.asum = 0
        self.count = 0
```

Note that:

- `nanmean_2d_float64_axis0` keeps the same name and signature as in the current code.
- `reduce_2d_float64_axis0` can be (re)used with any reduce function such as
nansum or median.
- The algo, here `Nanmean`, only has to be written for the 1d case.

To add a new function, the user only has to think about the 1d case and then write the algo class (I've never written a cython class but I assume it can be done). Bottleneck should take care of the rest.

A similar setup would be used for moving window functions.

I can't picture what all this would look like in practice, but just wanted to record the thought.

**Comment by shoyer** [comment]
@kwgoodman It looks like you've been making steady progress on the rewrite branch, but I stumble across an (ancient/closed) numpy pull request that implemented `nansum` and other aggregation functions as numpy ufuncs that I thought you might find interesting. It's written in C: https://github.com/numpy/numpy/pull/30/files

**Comment by kwgoodman** [comment]
I'm curious about how performance compares (bottleneck rewrite versus numpy pull request) if anyone is interested in testing.

**Comment by shoyer** [comment]
Have you seen Cython's fused types? http://docs.cython.org/src/userguide/fusedtypes.html

Using fused types like integer and float could be a nice way to remove a lot of redundancy in this rewrite.

**Comment by kwgoodman** [comment]
Yep, fused types are in the rewrite branch. But I ended up removing them. I forget the exact issue. That was at an early stage of the rewrite. So it might be a good idea to revisit and rediscover what, if any, issues there are.

**Comment by kwgoodman** [comment]
I need to finish up, ugh, the docstrings. The addition of `min_count` means a rewrite of the moving window docstrings. I'm kinda burned out on the rewrite at this point, so any and all suggestions welcomed on this moving window docstring template:

    """
    Moving window sum along the specified axis, optionally ignoring NaNs.

    Parameters
    ----------
    arr : ndarray
        Input array. If `arr` is not an array, a conversion is attempted.
    window : int
        The number of elements in the moving window.
    min_count: {int, None}, optional
        If the number of non-NaN values in a window is less than `min_count`,
        then a value of NaN is assigned to the window. By default `min_count`
        is None, which is equivalent to setting `min_count` equal to `window`.
    axis : int, optional
        The axis over which the window is moved. By default the last axis
        (axis=-1) is used. An axis of None is not allowed.

    Returns
    -------
    y : ndarray
        The moving sum of the input array along the specified axis. The output
        has the same shape as the input.

    Examples
    --------
    >>> arr = np.array([1.0, 2.0, 3.0, np.nan, 5.0])
    >>> bn.move_nansum(arr, window=2)
    array([ nan,   3.,   5.,  nan,  nan])
    >>> bn.move_sum(arr, window=2, min_count=1)
    array([ 1.,  3.,  5.,  3.,  5.])

    """

**Comment by kwgoodman** [comment]
I merged the rewrite branch into master.
