### ISSUE TITLE
Regression in performance for nanmedian since 0.8.0 release

### ISSUE THREAD

**Issue by jennolsen84** [kwgoodman/bottleneck#95]
Hi, I noticed that nanmedian and median was about 20% slower in master than 0.8.0.  I also noticed this with the recent code rewrite branch.

Not sure if everyone is seeing this, but wanted to bring it up before the 1.0 release.  Python 3.4+ on Ubuntu 14.10

**Comment by kwgoodman** [comment]
I am glad you are comparing branches and versions.

The rewrite branch does not yet contain nanmedian. The slowdown from 0.8.0 to master may be from #91.

When nanmedian gets added to the rewrite branch, please retest. The relative performance will depend on the shape of the array and the axis, so include an example.

**Comment by kwgoodman** [comment]
I added median and nanmedian to the rewrite branch. So you can re-run the test if you are up for it.

**Comment by jennolsen84** [comment]
The first run looks good, I will run it again in a couple of minutes and post those results too.  The data type is double, and I am calling it on a square matrix (of NxN) and using timeit

```
bn.version = 0.8.0

median
4000x4000
10 loops, best of 3: 154 msec per loop
2000x2000
10 loops, best of 3: 36.2 msec per loop
1000x1000
100 loops, best of 3: 8.62 msec per loop
500x500
100 loops, best of 3: 1.99 msec per loop

nanmedian
4000x4000
10 loops, best of 3: 137 msec per loop
2000x2000
10 loops, best of 3: 38.7 msec per loop
1000x1000
100 loops, best of 3: 6.79 msec per loop
500x500
100 loops, best of 3: 2.04 msec per loop


bn.version = 1.0.0dev

median
4000x4000
10 loops, best of 3: 136 msec per loop
2000x2000
10 loops, best of 3: 36.1 msec per loop
1000x1000
100 loops, best of 3: 8.58 msec per loop
500x500
100 loops, best of 3: 1.49 msec per loop

nanmedian
4000x4000
10 loops, best of 3: 144 msec per loop
2000x2000
10 loops, best of 3: 43.3 msec per loop
1000x1000
100 loops, best of 3: 7.25 msec per loop
500x500
100 loops, best of 3: 1.88 msec per loop
```

**Comment by jennolsen84** [comment]
The measurement seems a bit noisy.  Also, there are no nans in the dataset, so the branch predictor should've had a goot hit rate.  I am running it on my desktop, but tried to close down all other programs.  Still running X though.  

My CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
cache size	: 8192 KB
free -g shows 16GB of RAM free, so everything should've fit in ram easily

```
bn.version = 0.8.0

median
4000x4000
10 loops, best of 3: 152 msec per loop
2000x2000
10 loops, best of 3: 29 msec per loop
1000x1000
100 loops, best of 3: 6.98 msec per loop
500x500
100 loops, best of 3: 2.2 msec per loop

nanmedian
4000x4000
10 loops, best of 3: 146 msec per loop
2000x2000
10 loops, best of 3: 32 msec per loop
1000x1000
100 loops, best of 3: 9.49 msec per loop
500x500
100 loops, best of 3: 2.15 msec per loop

bn.version = 1.0.0dev

median
4000x4000
10 loops, best of 3: 135 msec per loop
2000x2000
10 loops, best of 3: 33.7 msec per loop
1000x1000
100 loops, best of 3: 8.82 msec per loop
500x500
100 loops, best of 3: 1.7 msec per loop

nanmedian
4000x4000
10 loops, best of 3: 167 msec per loop
2000x2000
10 loops, best of 3: 31.5 msec per loop
1000x1000
100 loops, best of 3: 9.42 msec per loop
500x500
100 loops, best of 3: 2.09 msec per loop
```

**Comment by kwgoodman** [comment]
On my slow (i7-2600k) box with ubuntu 14.04 I get:

```
In [1]: a=np.random.RandomState(4).rand(1000, 1000)
In [2]: timeit bn.nanmedian(a)
100 loops, best of 3: 10.7 ms per loop
In [3]: timeit bn.nanmedian(a, 0)
10 loops, best of 3: 24.7 ms per loop
In [4]: timeit bn.nanmedian(a, 1)
100 loops, best of 3: 12 ms per loop
```

What axis, if any, did you use?

**Comment by jennolsen84** [comment]
I did not use an axis
