### ISSUE TITLE
Does the rewrite of bottleneck work with pandas?

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#96]
I completely rewrote bottleneck.

Release notes: https://github.com/kwgoodman/bottleneck/blob/master/RELEASE.rst
Branch: master

@jreback, can one of the pandas developers see if the rewrite works with pandas?

**Comment by shoyer** [comment]
Just ran this locally on pandas 0.15.2 and encountered one issue, not directly related to the rewrite: `bottleneck.nansum` returns 0 for all NaN arrays (like `numpy.nansum`), which breaks a test in pandas which relied on the old behavior.

**Comment by shoyer** [comment]
I'm also running a larger test (using all the build permutations supported by the pandas CI infrastructure) on Travis, but I expect it will just turn up the same issue I found locally: https://travis-ci.org/shoyer/pandas/builds/49414524

By the way, I am definitely impressed by build times with the new bottleneck. It's very fast now!

**Comment by kwgoodman** [comment]
Thanks for the tests!

Hmm. Do you think pandas would be interested in following numpy and returning 0 for all NaN sums?

**Comment by kwgoodman** [comment]
BTW, I merged the rewrite branch into master.

**Comment by kwgoodman** [comment]
Oh, I was wondering if you thought any of the moving window functions could be used in pandas now that bottleneck has a min_count input (like minp in pandas).
