### ISSUE TITLE
Robustness of `move_std`

### ISSUE THREAD

**Issue by jaimefrio** [kwgoodman/bottleneck#99]
The algorithm used by `move_std` is prone to numerical errors. A while back I rewrote the implementation of the equivalent function in Pandas to use what some call [Welford's method](http://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online_algorithm), a one pass stable algorithm, see [here](https://github.com/pydata/pandas/pull/6817) for the relevant PR. I took some timings on the Pandas code, and it resulted in a 25% slowdown.

Would you like to see something like that implemented for bottleneck?

**Comment by kwgoodman** [comment]
Sounds like a good idea to me. But I'd like to hear what others think. Anyone?

bn.nanstd uses a two-pass algorithm. If the bottleneck is memory access, which I believe it is, then perhaps the one-pass algorithm you are proposing is faster. If so, assuming comparable stability, then maybe the place to start is with bn.nanstd?

**Comment by jaimefrio** [comment]
If you are not frontally opposed to it I'll put a PR together, and we can discuss its merits after it is up and running.

**Comment by kwgoodman** [comment]
That's great. Is this for ``move_std`` or ``nanstd``?

**Comment by jaimefrio** [comment]
I think it is only clearly advantageous in `move_std`, the two pass algorithm is typically faster, and probably even more accurate, for a non-moving window.

**Comment by shoyer** [comment]
Indeed, this seems like a nice improvement :+1:.

**Comment by jaimefrio** [comment]
What should go into the PR? Just the `move,pyx` file in `templates`, or the generated C files as well?
